name: metropulse
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  intl: 0.20.2
  flutter_riverpod: ^3.0.0
  state_notifier: ^1.0.0
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.1.10
  uni_links: ^0.5.1
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
